### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bonyhardian** [dandar3/android-google-firebase-README#1]
at google-firebase-iid Manifest.
Tag <permission> attribute name has invalid character '$'.

The container 'Android Dependencies' references non existing library:
\google-firebase-analytics-impl\bin\google-firebase-analytics-impl.jar'	
google-firebase-analytics
Build Path Problem

**Comment by dandar3** [comment]
@bonyhardian 
I will try to add all wiki articles in a section so you can all see them at once, but for now, as you can see the error is with `google-firebase-iid` project. 

The notes on the project [`dandar3/google-firebase-iid`](https://github.com/dandar3/android-google-firebase-iid/tree/9.8.0) are telling you to replace `${applicationId}` with your app Java package in `AndroidManifest.xml` (Android Studio does that for you, I'm not aware of a plugin or builder doing this for Eclipse yet).

You seem to want to implement Analytics or Ads from the error message - just a heads up `android-google-firebase-common` has the same problem.

**Comment by bonyhardian** [comment]
Thanks bro, problem solved.

I copied **google-firebase-analytics-impl.jar** from lib folder to bin folder.
I want to implement analytics and read from your blog (http://dandar3.blogspot.co.id/2016/11/eclipse-integrate-firebase-analytics.html).

And, how to generate **google-services.json** to **xml**?
Do you have a simple tutorial?

Thank you very much

**Comment by dandar3** [comment]
You don't need to copy anything - all you need to do is import the projects into your workspace (see the videos at the end of the android-google-firebase-README project). When Eclipse builds a project it will copy what it needs to \bin folder - anything you put in there will be removed on the next project clean / build.

You mentioned my blog post - see the **Importing google-services.json** section, it has a link to Google's documentation, it's called [Processing the JSON File ](https://firebase.google.com/docs/reference/gradle/#processing_the_json_file).

Hope you can work it out!

**Comment by bonyhardian** [comment]
So, we must use Android Studio to process the JSON file?
Or, do you know another way?

Thank you

**Comment by dandar3** [comment]
Letting Android Studio generating it for you it's one way, but not the only way.

The other way is to open the link, read the page, open the JSON file, look at the XML in Google's page and my blog post and you might see the resemblence 😄 

If not, then maybe you should use Android Studio to generate it for you.

**Comment by bonyhardian** [comment]
In the Prerequisites you wrote:
Manual processing of google-services.json into **values.xml** and **global_tracker.xml**.
I got the value.xml from your example, but how about **global_tracker.xml**?

Sorry if too many questions, I am new in Firebase.

Thank you very much

**Comment by dandar3** [comment]
Thanks for letting me know - I've updated that section in README.md on this project, that doesn't seem to be needed (looked like the Google Analytics tracking id which I believe is not used in Firebase anyway and it doesn't seem to be in the JSON file either).

That was a discrepancy between the first document I found:
https://developers.google.com/android/guides/google-services-plugin#processing_the_json_file

and the new one I found later:
https://firebase.google.com/docs/reference/gradle/#processing_the_json_file

**Comment by bonyhardian** [comment]
Is there any code to include on activity?

**Comment by dandar3** [comment]
You might want to start reading the [Firebase Analytics - Get Started](https://firebase.google.com/docs/analytics/android/start/) documentation, and the code in [firebase/quickstart-android](https://github.com/firebase/quickstart-android/blob/master/analytics/app/src/main/java/com/google/firebase/quickstart/analytics/MainActivity.java#L73-L73) GitHub repository. 

Past the point where you include the libraries yourself and manually convert the google-services.json, everything else is and should be the same really, so you can follow the standard documentation.

**Comment by dandar3** [comment]
@bonyhardian 
Have you got it working, are you ok now?
