### ISSUE TITLE
‘android-google-play-services-tagmanager-v4-impl’ is not use in Firebase Analytics？

### ISSUE THREAD

**Issue by wenqiangtxc** [dandar3/android-google-firebase-README#2]
I am using FireBase in Eclipse Android Project，Thanks for your the project,
but I found the ‘android-google-play-services-tagmanager-v4-impl’ below the 'Firebase Analytics'  not used in project.

**Comment by dandar3** [comment]
`google-play-services-tagmanager-v4-impl` is a dependency of the `google-play-services-analytics` project, you can see `ANDROID_SDK\extras\google\m2repository\com\google\android\gms\play-services-analytics\10.2.1\play-services-analytics-10.2.1.pom` for example.

I searched through all 10.2.1 files and I can only see it referenced by the `google-play-services-analytics` project, which is what I would expect. `google-firebase-analytics` doesn't dependend on `google-play-services-analytics` (anymore). What version do you use?

If you found that it works without it, it's fine - I only included it cause it was mentioned as a dependency and wanted to avoid runtime issues. Try deleting the `android-google-play-services-tagmanager-v4-impl` and Eclipse should tell you which project needs it.

**Comment by wenqiangtxc** [comment]
I am using version is 10.2.1 for my demo, I also using google-play-services-analytics,but my project runtime report an error:`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzac`

**Comment by dandar3** [comment]
[gvenzl/ClassFinder](https://github.com/gvenzl/ClassFinder)
`java -jar ClassFinder-2.0.0-runnable.jar`
File / Folder: `your workspace location`
Class name : `com.google.android.gms.common.internal.zzac`
Location -> `[...]\google-play-services-basement\libs\google-play-services-basement.jar`

If you're using Eclipse it should have the projects linked to each other and complain if you're missing `google-play-services-basement` project from the workspace? Did you manually downloaded each project yourself or did you download as project sets? (https://www.youtube.com/watch?v=ytRSnjp56tA)

**Comment by wenqiangtxc** [comment]
I solved my issues,The reason is 2 versions of android-support-v4.jar in my demo,`android-support-v4\libs\android-support-v4.jar` and `demo\libs\android-support-v4.jar`.I deleted the `demo\libs\android-support-v4.jar`,my project ran isrightly.

And I tried to remove `google-play-services-analytics` and `android-google-play-services-tagmanager-v4-impl`,It works fine.

Thank you very much.

**Comment by dandar3** [comment]
That would make sense - the classloader was loading the older `support-v4` library first overshadowing the newer version and then when other library was calling a new method, it would crash as not being found. Yes, you need to use compatible versions and to be consisent accross the library set.

It appears with the newer versions that Firebase libraries depend less on Play Services SDK libraries, and you are correct, Firebase Analytics doesn't seem to be depending on `google-play-services-analytics` anymore and the second is probably you not hitting the specific functionality (https://developers.google.com/tag-manager/android/v5/)
