### ISSUE TITLE
Enable firecrash

### ISSUE THREAD

**Issue by ntimesc** [dandar3/android-google-firebase-README#3]
I tried to use your libraries provided on following links to configure Firebase in eclipse 

https://github.com/dandar3/android-google-firebase-README

I am able to use the Firebase Analytics properly but i want to use FirebaseCrash. 

so do you have any eclipse project created for FirebaseCrash as i tried to extract the jar from and add it into my eclipse project

C:\Program Files (x86)\Android\android-sdk\extras\google\m2repository\com\google\firebase\firebase-crash

but i am getting following entries in my cat logs and not able to view any entries in Crash Reports over firebase console

05-12 18:46:52.666: I/FirebaseCrashApiImpl(18953): FirebaseCrashApiImpl created by ClassLoader p[DexPathList[[zip file 
"/data/data/com.google.android.gms/app_chimera/m/00000007/DynamiteModulesC_GmsCore_prodlmp_alldpi_release.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]

05-12 18:46:52.834: I/FirebaseCrash(18953): FirebaseCrash reporting initialized com.google.android.gms.internal.zzbnq@3e77b92d

05-12 18:47:01.546: I/FA(18953): Tag Manager is not found and thus will not be used

so do you have any eclipse project for FirebaseCrash or can you please help me to make it work

**Comment by dandar3** [comment]
Sorry for the late response, been busy with fixing 10.2.4 release and been away for the last week, looking into it right now for 10.2.6

**Comment by dandar3** [comment]
**Firebase Crash Reporting** now part of 10.2.6 release, let me know how it works for you.
https://github.com/dandar3/android-google-firebase-README/tree/10.2.6
