### ISSUE TITLE
Proguard: can't find superclass or interface org.apache.http.client.methods.HttpEntityEnclosingRequestBase

### ISSUE THREAD

**Issue by dandar3** [dandar3/android-google-firebase-README#4]
Hey Dan,

have you ever done a release build with firebase messaging libs included? I have massive problems with proguard when obfuscating. It throws a lot of Warnings like

```
Warning: com.google.android.gms.internal.zzw$zza: can't find superclass or interface org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzac: can't find referenced class android.net.http.AndroidHttpClient
Warning: com.google.android.gms.internal.zzac: can't find referenced class android.net.http.AndroidHttpClient

Ant build can not be finished with: Please correct the above warnings first.
```

**Comment by dandar3** [comment]
First I should say I don't have a released version using Firebase Messaging, but I think it should work. 

As it just happens I already had a line in my proguard config file telling it to ignore these errors:
```
# Already present in the Android runtime.
-dontwarn org.apache.http.**
```

Alternatively I would follow the suggestion from this StackOverflow thread to add to your project classpath the `android-sdk\platforms\android-25\optional\org.apache.http.legacy.jar` into your app `libs` folder. https://stackoverflow.com/a/35393228/308836

**Comment by dandar3** [comment]
Note: The issue is not new and it appears to relate to the classes in `google-play-services-basement` so it affects everything Google Play Services and Firebase really.

And it is nothing new, the issue has been reported before and suggestion is coming from comment #21 on Sep 2015.
> Posted on Sep 17, 2015 by Quick Hippo
> There won't be a fix... As a Würgaround for Eclips you could add platforms/android-23/optional/org.apache.http.legacy.jar to libs

https://code.google.com/archive/p/android-developer-preview/issues/3001

**Comment by dud3rin0** [comment]
Thx for adding the issue.
i'll have another try on it although i thought i was already through the advices like adding -dontwarns or adding the apache http lib. 
i will let you know if it worked.
also i will add some more compile output and infos about the build system asap

**Comment by dandar3** [comment]
Started working on the [ProgGuard](https://github.com/dandar3/android-google-firebase-README/wiki/ProGuard) wiki pages, there's one issue remaining where I need to move a string to the `basement` library (had to do that for about 7 libraries cause Google assumes they will all get merged at compile time in `com.google.android.gms` by Android Studio, madness) and once that's done I'll get back.

**Comment by dud3rin0** [comment]
got to manage the build now.
it was all about proguard configs in my app.

this is my proguard.cfg

```
-keepattributes Signature
-keep class com.firebase.** { *; }
-keep class org.apache.** { *; }
-keepnames class com.fasterxml.jackson.** { *; }
-keepnames class javax.servlet.** { *; }
-keepnames class org.ietf.jgss.** { *; }
-dontwarn org.apache.**
-dontwarn org.w3c.dom.**

-dontwarn android.support.v4.**
-dontwarn com.google.android.gms.**
-dontwarn com.google.firebase.**

-keep class * extends com.myCompany.package.flavor.Flavor { *; }
-keep class com.myCompany.** { *; }
```

Though after weeks of integrating fcm, and finally got that all built, we decided to migrate our projects to gradle. I'm curious what will be the problems there ^^

**Comment by dandar3** [comment]
Thanks for your feedback!

Yeah, well, this was all meant to be transitional anyway, you'll be fine, good luck! :-)
